### ISSUE TITLE
PHPSTORM怎么使用yasd调试

### ISSUE THREAD

**Issue by chenchen211** [swoole/yasd#115]
在phpstorm中按xdebug配置端口
![image](https://user-images.githubusercontent.com/20855447/115525139-69105d00-a2c1-11eb-88ab-114381f35318.png)
![image](https://user-images.githubusercontent.com/20855447/115525196-73caf200-a2c1-11eb-979b-35b36e239360.png)

开始调试时，链接为 http://localhost?XDEBUG_SESSION_START=19587， ide无法开始调试
![image](https://user-images.githubusercontent.com/20855447/115525379-9eb54600-a2c1-11eb-94a1-6b73a2a01d05.png)

**Comment by huanghantao** [comment]
你可以看这个视频：https://course.swoole-cloud.com/course-video/136

**Comment by juslintek** [comment]
I have the same problem, I've looked at the video. Have the same configs, have the latest PhpStorm, have Mac OS Big Sur, but it doesn't work with docker. https://github.com/swoole/swoole-src/issues/4166#issuecomment-829638495

Or with supervisor, not sure which one is to blame, haven't investigated. But if you want, I can try over my free time different setups and tell which ones work which ones don't. 

The comment, that I've posted above contains the first setup that I have tried. It is a big setup, but it covers multiple cases, a supervisor in docker, and PHPUnit testing. I have setup phpstorm to use `-e` when run in PHPStorm like this:

PHPUnit host side is working, but you kind of loose the phpstorm functionality for telling when tests are running in debug mode, because if "Start Listening for PHP Debug Connections" is on it catches all launches. As well it catches code from other projects that you might be running in parallel with same PHP that has yasd enabled in remote mode and `-e` flag is added for execution.

The biggest problem for me is that it doesn't work with supervisor. It seems that it ignores that executable was run using `php -e`.

:-(

**Comment by ipuppy2** [comment]
@chenchen211 哥们，你那边 OK 了吗?想请教一下。

**Comment by huanghantao** [comment]
@ipuppy2 有问题加我微信codinghuang

**Comment by ipuppy2** [comment]
@huanghantao 非常感谢，我找到了这个 issue, 根据上面的操作，配置成功了：
[https://github.com/swoole/yasd/issues/59](https://github.com/swoole/yasd/issues/59)

**Comment by drttcrh** [comment]
> https://course.swoole-cloud.com/course-video/136

### 视频不存在了 
<img width="1210" alt="image" src="https://user-images.githubusercontent.com/13195127/161382579-aca135c2-94b8-4ed9-be1a-e39d6b17ee3b.png">

**Comment by huanghantao** [comment]
可以考虑使用 swoole-src的 xdebug分支，https://github.com/swoole/swoole-src/tree/support-xdebug
可以直接使用xdebug进行调试，前提是PHP版本要大于等于8.1
